use_frameworks!

platform :ios, '8.0'

target 'YSHNetWorkTool_Example' do
  pod 'YSHNetWorkTool', :path => '../'
#pod 'YSHNetWorkTool',:git => 'git@github.com:QiuYeHong90/YSHNetWorkTool.git'
  target 'YSHNetWorkTool_Tests' do
    inherit! :search_paths

    
  end
end
